; Splash image path relative to uniloader script
; Debug skips launching the browser, displays message instead.
; ControlTerminal: If enabled, the terminal is minimized while the external app loads.

[User]
	browserDelay=3
	exitDelay=6
	maxTriesHTTP=8
	debug=False
	controlTerminal.state=Disabled

[ComfyUI_3]
	appName=ComfyUI_3
	port=8188
	ip=127.0.0.1
	path=L:\comfy_ui_3
	loaderScript=_start.bat
	splashImage=img\comfyui-02-splash.jpeg
	browserArgs=--profile-directory=Default --app-id=fdfllangmneamcbmopcnemepphpfaihc

[SillyTavern]
	appName=SillyTavern
	port=8000
	ip=127.0.0.1
	path=L:\SillyTavern
	loaderScript=Start.bat
	splashImage=img\tavern-splash-05.jpg
	browserArgs=--profile-directory=Default --app-id=mngloiodpbedloingimookgdhhkgcblo
