; Splash image path relative to uniloader script
; Debug skips launching the browser, displays message instead.

[User]
	exitDelay=8
	debug=False
	hideTerminal=Disabled
	browserPath=C:\Program Files\BraveSoftware\Brave-Browser\Application\chrome_proxy.exe

[ComfyUI_3]
	appName=ComfyUI_3
	port=8188
	ip=127.0.0.1
	path=L:\comfy_ui_3
	loaderScript=_start.bat
	splashImage=img\comfyui-03-splash.gif
	splashAnimationSpeed=0.45
	browserArgs=--profile-directory=Default --app-id=fdfllangmneamcbmopcnemepphpfaihc
	maxTriesHTTP=12

[SillyTavern]
	appName=SillyTavern
	port=8000
	ip=127.0.0.1
	path=L:\SillyTavern
	loaderScript=Start.bat
	splashImage=img\tavern-splash-06.gif
	splashAnimationSpeed=1.5
	browserArgs=--profile-directory=Default --app-id=mngloiodpbedloingimookgdhhkgcblo
	maxTriesHTTP=4
